import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <header>
          <h1 className="pt-6 text-4xl font-bold text-center">掲示板</h1>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
